### ISSUE TITLE
Do you think this algorithm work for all cases?

### ISSUE THREAD

**Issue by hiteshsai** [PradeepNalluri/Implementation-of-Back-Propagation-Algorithm#1]
I tried to apply to my dataset but its not working.

**Comment by PradeepNalluri** [comment]
It hopefully works for all types of data sets but pre-processing the dataset and setting the parameters will be crucial.

**Comment by hiteshsai** [comment]
Can you please elaborate more on what kind of parameters are suitable for this algorithm.
